### ISSUE TITLE
Button functionality in the app

### ISSUE THREAD

**Issue by arjunkalburgi** [ECE493Group3/personalstylist#2]
- [x] search in stylist

- [x] upload

- [x] remove images

- [x] Accept Reject client 

- [x] filter wardrobe/recommendedimages

- [x] select outfit for dressLog

**Comment by askalburgi** [comment]
- [ ] upload photos 

- [ ] search for an item

- [ ] Accept Reject client 

- [ ]

**Comment by askalburgi** [comment]
**Accept Client**
Remove from clientRequests
Add to clients 

**Remove Client**
Remove from clientRequests

**Comment by askalburgi** [comment]
**Search in Stylist**
Use filter on the button for that list of images

**Comment by arjunkalburgi** [comment]
**Upload images**
POST request to Cybera 

**Remove images**
POST request to Cybera

**Comment by askalburgi** [comment]
**Filter Wardrobe images**
Implement button/filter area 

**Filter Recommended images**
Implement button/filter area

**Comment by arjunkalburgi** [comment]
**Select Outfit**
On select button, push new dressLog in the user
